/**
 * 技能 Repository — CRUD 操作
 *
 * 管理技能的创建、查询、更新和删除。
 * 技能可以是用户手动创建的，也可以是 Agent 自动生成的。
 */

import { query, execute } from '../database'
import type { Skill } from '@shared/types'

interface SkillRow {
  id: string
  name: string
  description: string
  content: string
  auto_generated: number
  confidence: number
  status: string
  source_episodes: string | null
  embedding: string | null
  execution_count: number
  success_rate: number
  avg_duration: number | null
  created_at: number
  updated_at: number
}

/** 创建技能 */
export function createSkill(skill: {
  id: string
  name: string
  description: string
  content: string
  autoGenerated?: boolean
  confidence?: number
  status?: Skill['status']
  sourceEpisodes?: string[]
  embedding?: number[]
}): Skill {
  const now = Date.now()
  execute(
    `INSERT INTO skills
     (id, name, description, content, auto_generated, confidence, status,
      source_episodes, embedding, execution_count, success_rate, created_at, updated_at)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 0, 0, ?, ?)`,
    [
      skill.id,
      skill.name,
      skill.description,
      skill.content,
      skill.autoGenerated ? 1 : 0,
      skill.confidence ?? 0.5,
      skill.status ?? 'draft',
      skill.sourceEpisodes ? JSON.stringify(skill.sourceEpisodes) : null,
      skill.embedding ? JSON.stringify(skill.embedding) : null,
      now,
      now
    ]
  )
  return {
    id: skill.id,
    name: skill.name,
    description: skill.description,
    content: skill.content,
    autoGenerated: skill.autoGenerated ?? false,
    confidence: skill.confidence ?? 0.5,
    status: skill.status ?? 'draft',
    executionCount: 0,
    successRate: 0,
    createdAt: now,
    updatedAt: now
  }
}

/** 获取技能 */
export function getSkill(id: string): Skill | null {
  const rows = query<SkillRow>('SELECT * FROM skills WHERE id = ?', [id])
  if (rows.length === 0) return null
  return rowToSkill(rows[0])
}

/** 获取所有技能 */
export function getAllSkills(): Skill[] {
  const rows = query<SkillRow>('SELECT * FROM skills ORDER BY updated_at DESC')
  return rows.map(rowToSkill)
}

/** 获取活跃技能 */
export function getActiveSkills(): Skill[] {
  const rows = query<SkillRow>(
    "SELECT * FROM skills WHERE status = 'active' ORDER BY execution_count DESC"
  )
  return rows.map(rowToSkill)
}

/** 获取草稿技能（待确认的自动生成技能） */
export function getDraftSkills(): Skill[] {
  const rows = query<SkillRow>(
    "SELECT * FROM skills WHERE status = 'draft' ORDER BY created_at DESC"
  )
  return rows.map(rowToSkill)
}

/** 更新技能 */
export function updateSkill(id: string, updates: {
  name?: string
  description?: string
  content?: string
  confidence?: number
  status?: Skill['status']
}): void {
  const sets: string[] = []
  const params: unknown[] = []

  if (updates.name !== undefined) { sets.push('name = ?'); params.push(updates.name) }
  if (updates.description !== undefined) { sets.push('description = ?'); params.push(updates.description) }
  if (updates.content !== undefined) { sets.push('content = ?'); params.push(updates.content) }
  if (updates.confidence !== undefined) { sets.push('confidence = ?'); params.push(updates.confidence) }
  if (updates.status !== undefined) { sets.push('status = ?'); params.push(updates.status) }

  if (sets.length === 0) return

  sets.push('updated_at = ?')
  params.push(Date.now())
  params.push(id)

  execute(`UPDATE skills SET ${sets.join(', ')} WHERE id = ?`, params)
}

/** 更新技能执行统计 */
export function updateSkillStats(
  id: string,
  success: boolean,
  duration: number
): void {
  const skill = getSkill(id)
  if (!skill) return

  const newCount = skill.executionCount + 1
  const newSuccessRate = (skill.successRate * skill.executionCount + (success ? 1 : 0)) / newCount
  const oldAvg = 0 // 需要从数据库获取 avg_duration，但 Skill 类型没有此字段
  const newAvgDuration = (oldAvg * skill.executionCount + duration) / newCount

  execute(
    `UPDATE skills SET execution_count = ?, success_rate = ?, avg_duration = ?, updated_at = ? WHERE id = ?`,
    [newCount, newSuccessRate, newAvgDuration, Date.now(), id]
  )
}

/** 删除技能 */
export function deleteSkill(id: string): void {
  execute('DELETE FROM skills WHERE id = ?', [id])
}

/** 获取技能的嵌入向量 */
export function getSkillEmbedding(id: string): number[] | null {
  const rows = query<{ embedding: string | null }>(
    'SELECT embedding FROM skills WHERE id = ?',
    [id]
  )
  if (!rows[0]?.embedding) return null
  try {
    return JSON.parse(rows[0].embedding)
  } catch {
    return null
  }
}

/** 更新技能嵌入向量 */
export function updateSkillEmbedding(id: string, embedding: number[]): void {
  execute(
    'UPDATE skills SET embedding = ? WHERE id = ?',
    [JSON.stringify(embedding), id]
  )
}

/** 行转对象 */
function rowToSkill(row: SkillRow): Skill {
  return {
    id: row.id,
    name: row.name,
    description: row.description,
    content: row.content,
    autoGenerated: !!row.auto_generated,
    confidence: row.confidence,
    status: row.status as Skill['status'],
    executionCount: row.execution_count,
    successRate: row.success_rate,
    createdAt: row.created_at,
    updatedAt: row.updated_at
  }
}
