/**
 * 技能存储与匹配 — 管理技能的生命周期
 *
 * 核心功能:
 * 1. 技能存储 — 将生成的技能持久化到 SQLite
 * 2. 技能匹配 — 根据用户查询匹配最相关的技能（向量相似度）
 * 3. 技能加载 — 将匹配的技能注入 Agent 上下文
 * 4. 技能统计 — 跟踪技能使用次数和成功率
 *
 * 匹配流程:
 * 1. 加载所有活跃技能及其嵌入向量
 * 2. 计算用户查询与每个技能的余弦相似度
 * 3. 按相似度排序，返回 Top-K 技能
 * 4. 将技能内容注入系统提示词
 */

import { generateEmbedding } from '../memory/embeddings'
import { cosineSimilarity } from '../memory/vector-store'
import {
  createSkill,
  getActiveSkills,
  getSkillEmbedding,
  updateSkillEmbedding,
  updateSkillStats,
  getAllSkills,
  updateSkill
} from '../../src/main/storage/repositories/skills'
import { generateSkill } from './skill-generator'
import type { DetectedPattern } from './pattern-detector'
import type { SkillMatchResult, SkillDef } from '../skills/types'

/** 技能匹配选项 */
export interface SkillMatchOptions {
  topK: number
  minScore: number
}

/** 默认匹配参数 */
const DEFAULT_OPTIONS: SkillMatchOptions = {
  topK: 3,
  minScore: 0.6
}

/**
 * 技能存储管理器
 */
export class SkillStore {
  /**
   * 从检测到的模式创建技能
   *
   * @param pattern 检测到的模式
   * @param signal AbortSignal
   * @returns 创建的技能 ID（如果创建成功）
   */
  async createFromPattern(
    pattern: DetectedPattern,
    signal?: AbortSignal
  ): Promise<string | null> {
    try {
      const result = await generateSkill(pattern, signal)
      const { proposal, embedding } = result

      // 存储到数据库
      const skillId = `skill-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`
      createSkill({
        id: skillId,
        name: proposal.name,
        description: proposal.description,
        content: proposal.content,
        autoGenerated: true,
        confidence: proposal.confidence,
        status: 'active',  // 自动生成的技能直接设为活跃
        sourceEpisodes: proposal.sourceEpisodes,
        embedding
      })

      console.log(`[SkillStore] Created skill: ${skillId} (${proposal.name})`)
      return skillId
    } catch (err) {
      console.error('[SkillStore] Failed to create skill from pattern:', err)
      return null
    }
  }

  /**
   * 匹配技能 — 根据用户查询找到最相关的技能
   *
   * @param query 用户查询
   * @param options 匹配选项
   * @param signal AbortSignal
   * @returns 匹配结果列表
   */
  async match(
    query: string,
    options?: Partial<SkillMatchOptions>,
    signal?: AbortSignal
  ): Promise<SkillMatchResult[]> {
    const opts = { ...DEFAULT_OPTIONS, ...options }

    const activeSkills = getActiveSkills()
    if (activeSkills.length === 0) return []

    try {
      // 生成查询向量
      const queryEmbedding = await generateEmbedding(query, signal)

      const results: SkillMatchResult[] = []

      for (const skill of activeSkills) {
        // 获取技能的嵌入向量
        let skillEmbedding = getSkillEmbedding(skill.id)
        if (!skillEmbedding) {
          // 技能没有嵌入向量，生成一个
          skillEmbedding = await generateEmbedding(
            `${skill.name} ${skill.description} ${skill.content}`,
            signal
          )
          updateSkillEmbedding(skill.id, skillEmbedding)
        }

        const score = cosineSimilarity(queryEmbedding, skillEmbedding)
        if (score < opts.minScore) continue

        results.push({
          skill: {
            id: skill.id,
            name: skill.name,
            description: skill.description,
            content: skill.content,
            autoGenerated: skill.autoGenerated,
            confidence: skill.confidence,
            status: skill.status as SkillDef['status'],
            sourceEpisodes: [],
            executionCount: skill.executionCount,
            successRate: skill.successRate,
            avgDuration: 0,
            createdAt: skill.createdAt,
            updatedAt: skill.updatedAt
          },
          score,
          loaded: false,
          reason: `向量相似度: ${(score * 100).toFixed(0)}%`
        })
      }

      // 按相似度排序
      results.sort((a, b) => b.score - a.score)

      // 标记被加载的技能
      const top = results.slice(0, opts.topK)
      for (const r of top) {
        r.loaded = true
      }

      return top
    } catch (err) {
      console.error('[SkillStore] Match failed:', err)
      return []
    }
  }

  /**
   * 格式化技能为上下文文本
   *
   * 将匹配的技能格式化为可注入 LLM 上下文的文本。
   *
   * @param matches 匹配结果
   * @returns 格式化的技能文本
   */
  formatForContext(matches: SkillMatchResult[]): string {
    if (matches.length === 0) return ''

    const sections = matches.map((m, i) => {
      return `### 技能 ${i + 1}: ${m.skill.name}
${m.skill.description}

${m.skill.content}`
    })

    return `[可用技能]
以下技能可能与用户问题相关，请参考技能内容提供更专业的回答：

${sections.join('\n\n')}`
  }

  /**
   * 记录技能执行结果
   *
   * @param skillId 技能 ID
   * @param success 是否成功
   * @param duration 执行时长（毫秒）
   */
  recordExecution(skillId: string, success: boolean, duration: number): void {
    updateSkillStats(skillId, success, duration)
  }

  /**
   * 手动创建技能
   */
  create(
    name: string,
    description: string,
    content: string
  ): string {
    const skillId = `skill-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`
    createSkill({
      id: skillId,
      name,
      description,
      content,
      autoGenerated: false,
      confidence: 1.0,
      status: 'active'
    })
    return skillId
  }

  /**
   * 获取所有技能
   */
  getAll() {
    return getAllSkills()
  }

  /**
   * 更新技能
   */
  update(id: string, updates: {
    name?: string
    description?: string
    content?: string
    status?: SkillDef['status']
  }): void {
    updateSkill(id, updates)
  }

  /**
   * 获取技能统计
   */
  getStats(): {
    total: number
    active: number
    autoGenerated: number
  } {
    const all = getAllSkills()
    return {
      total: all.length,
      active: all.filter(s => s.status === 'active').length,
      autoGenerated: all.filter(s => s.autoGenerated).length
    }
  }
}

// ── 单例 ──
export const skillStore = new SkillStore()
