/**
 * 技能系统类型定义
 */

export interface SkillDef {
  id: string
  name: string
  description: string
  content: string
  autoGenerated: boolean
  confidence: number
  status: 'active' | 'draft' | 'disabled' | 'rejected'
  sourceEpisodes: string[]
  executionCount: number
  successRate: number
  avgDuration: number
  createdAt: number
  updatedAt: number
  embedding?: number[]
}

/** 技能匹配结果 */
export interface SkillMatchResult {
  skill: SkillDef
  score: number
  loaded: boolean
  reason: string
}

/** 技能自动生成提议 */
export interface SkillProposal {
  id: string
  name: string
  description: string
  content: string
  confidence: number
  sourceEpisodes: string[]
  createdAt: number
  status: 'pending' | 'accepted' | 'rejected'
}

/** 模式检测信号 */
export interface PatternSignal {
  type: 'action_sequence' | 'query_similarity' | 'tool_combination'
  occurrences: string[]
  similarity: number
  lastSeen: number
}
