<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import type { Skill } from '@shared/types'

// ── 状态 ──
const loading = ref(true)
const skills = ref<Skill[]>([])
const errorMsg = ref('')
const successMsg = ref('')

// ── 筛选 ──
const filterStatus = ref<'all' | Skill['status']>('all')
const searchQuery = ref('')

// ── 编辑/创建 ──
const editingSkill = ref<Skill | null>(null)
const showEditModal = ref(false)
const isCreating = ref(false)

// ── 筛选后的技能 ──
const filteredSkills = computed(() => {
  let result = skills.value
  if (filterStatus.value !== 'all') {
    result = result.filter(s => s.status === filterStatus.value)
  }
  if (searchQuery.value.trim()) {
    const q = searchQuery.value.toLowerCase()
    result = result.filter(s =>
      s.name.toLowerCase().includes(q) ||
      s.description.toLowerCase().includes(q)
    )
  }
  return result
})

// ── 统计 ──
const stats = computed(() => ({
  total: skills.value.length,
  active: skills.value.filter(s => s.status === 'active').length,
  draft: skills.value.filter(s => s.status === 'draft').length,
  disabled: skills.value.filter(s => s.status === 'disabled').length
}))

// ── 加载技能列表 ──
async function loadSkills() {
  loading.value = true
  errorMsg.value = ''
  try {
    skills.value = await window.skillsAPI.list()
  } catch (err) {
    errorMsg.value = '加载技能列表失败'
    console.error(err)
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  loadSkills()
})

// ── 创建新技能 ──
function handleCreate() {
  editingSkill.value = {
    id: '',
    name: '',
    description: '',
    content: '',
    autoGenerated: false,
    confidence: 0.5,
    status: 'active',
    executionCount: 0,
    successRate: 0,
    createdAt: 0,
    updatedAt: 0
  }
  isCreating.value = true
  showEditModal.value = true
}

// ── 编辑技能 ──
function handleEdit(skill: Skill) {
  editingSkill.value = { ...skill }
  isCreating.value = false
  showEditModal.value = true
}

// ── 保存技能 ──
async function handleSave() {
  if (!editingSkill.value) return
  if (!editingSkill.value.name.trim()) {
    errorMsg.value = '请填写技能名称'
    return
  }
  if (!editingSkill.value.description.trim()) {
    errorMsg.value = '请填写技能描述'
    return
  }

  errorMsg.value = ''
  try {
    if (isCreating.value) {
      await window.skillsAPI.create({
        name: editingSkill.value.name,
        description: editingSkill.value.description,
        content: editingSkill.value.content,
        status: editingSkill.value.status
      })
      successMsg.value = '技能创建成功'
    } else {
      await window.skillsAPI.update(editingSkill.value.id, {
        name: editingSkill.value.name,
        description: editingSkill.value.description,
        content: editingSkill.value.content,
        status: editingSkill.value.status
      })
      successMsg.value = '技能更新成功'
    }
    showEditModal.value = false
    editingSkill.value = null
    setTimeout(() => { successMsg.value = '' }, 2000)
    await loadSkills()
  } catch (err) {
    errorMsg.value = '保存失败'
    console.error(err)
  }
}

// ── 删除技能 ──
async function handleDelete(skill: Skill) {
  if (!confirm(`确定删除技能「${skill.name}」？`)) return
  try {
    await window.skillsAPI.remove(skill.id)
    successMsg.value = '技能已删除'
    setTimeout(() => { successMsg.value = '' }, 2000)
    await loadSkills()
  } catch (err) {
    errorMsg.value = '删除失败'
    console.error(err)
  }
}

// ── 切换技能状态 ──
async function toggleStatus(skill: Skill) {
  const newStatus: Skill['status'] = skill.status === 'active' ? 'disabled' : 'active'
  try {
    await window.skillsAPI.update(skill.id, { status: newStatus })
    await loadSkills()
  } catch (err) {
    errorMsg.value = '更新状态失败'
    console.error(err)
  }
}

// ── 关闭窗口 ──
function handleClose() {
  window.skillsAPI.close()
}

// ── 格式化时间 ──
function formatTime(ts: number): string {
  if (!ts) return '-'
  return new Date(ts).toLocaleString('zh-CN', {
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit'
  })
}

// ── 状态标签 ──
const statusLabels: Record<Skill['status'], string> = {
  active: '活跃',
  draft: '草稿',
  disabled: '已禁用',
  rejected: '已拒绝'
}
</script>

<template>
  <div class="skills-root" data-testid="skills-root">
    <!-- ═══ 标题栏 ═══ -->
    <div class="title-bar" data-testid="title-bar">
      <div class="title-left">
        <span class="title-owl">🦉</span>
        <span class="title-text">技能管理</span>
      </div>
      <div class="title-right">
        <button class="title-btn" data-testid="btn-close-skills" title="关闭" @click="handleClose">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M18 6L6 18M6 6l12 12"/>
          </svg>
        </button>
      </div>
    </div>

    <!-- ═══ 内容区 ═══ -->
    <div class="skills-content" v-if="!loading">
      <!-- 统计栏 -->
      <div class="stats-bar" data-testid="stats-bar">
        <div class="stat-item">
          <span class="stat-value">{{ stats.total }}</span>
          <span class="stat-label">总计</span>
        </div>
        <div class="stat-item">
          <span class="stat-value active">{{ stats.active }}</span>
          <span class="stat-label">活跃</span>
        </div>
        <div class="stat-item">
          <span class="stat-value draft">{{ stats.draft }}</span>
          <span class="stat-label">草稿</span>
        </div>
        <div class="stat-item">
          <span class="stat-value disabled">{{ stats.disabled }}</span>
          <span class="stat-label">已禁用</span>
        </div>
      </div>

      <!-- 搜索 + 筛选 + 创建 -->
      <div class="toolbar">
        <input
          type="text"
          class="search-input"
          data-testid="search-input"
          v-model="searchQuery"
          placeholder="搜索技能..."
        />
        <select class="filter-select" data-testid="filter-select" v-model="filterStatus">
          <option value="all">全部</option>
          <option value="active">活跃</option>
          <option value="draft">草稿</option>
          <option value="disabled">已禁用</option>
          <option value="rejected">已拒绝</option>
        </select>
        <button class="btn-add" data-testid="btn-add-skill" @click="handleCreate">
          + 新建技能
        </button>
      </div>

      <!-- 提示消息 -->
      <div v-if="errorMsg" class="error-msg" data-testid="error-msg">{{ errorMsg }}</div>
      <div v-if="successMsg" class="success-msg" data-testid="success-msg">{{ successMsg }}</div>

      <!-- 空状态 -->
      <div v-if="filteredSkills.length === 0" class="empty-state" data-testid="empty-skills">
        <p>暂无技能</p>
        <p class="hint">点击「新建技能」创建第一个技能</p>
      </div>

      <!-- 技能列表 -->
      <div v-else class="skill-list" data-testid="skill-list">
        <div
          v-for="skill in filteredSkills"
          :key="skill.id"
          class="skill-card"
          :class="{ disabled: skill.status === 'disabled' }"
          :data-testid="`skill-card-${skill.id}`"
        >
          <div class="skill-header">
            <div class="skill-title-row">
              <span class="skill-name" data-testid="skill-name">{{ skill.name }}</span>
              <span class="skill-status-badge" :class="skill.status">{{ statusLabels[skill.status] }}</span>
              <span v-if="skill.autoGenerated" class="auto-tag" title="自动生成">⚡</span>
            </div>
            <div class="skill-actions">
              <button class="btn-icon" @click="toggleStatus(skill)"
                      :title="skill.status === 'active' ? '禁用' : '启用'">
                {{ skill.status === 'active' ? '🚫' : '👁' }}
              </button>
              <button class="btn-icon" data-testid="btn-edit-skill" @click="handleEdit(skill)" title="编辑">
                ✏️
              </button>
              <button class="btn-icon" data-testid="btn-delete-skill" @click="handleDelete(skill)" title="删除">
                🗑
              </button>
            </div>
          </div>
          <div class="skill-description">{{ skill.description }}</div>
          <div class="skill-meta">
            <span class="meta-item">使用 {{ skill.executionCount }} 次</span>
            <span class="meta-item">成功率 {{ (skill.successRate * 100).toFixed(0) }}%</span>
            <span class="meta-item">更新于 {{ formatTime(skill.updatedAt) }}</span>
          </div>
        </div>
      </div>
    </div>

    <div v-else class="loading-state">
      <div class="spinner"></div>
      <p>加载中...</p>
    </div>

    <!-- ═══ 编辑/创建弹窗 ═══ -->
    <div v-if="showEditModal" class="modal-overlay" data-testid="skill-modal" @click.self="showEditModal = false">
      <div class="modal-content">
        <div class="modal-header">
          <h3>{{ isCreating ? '新建技能' : '编辑技能' }}</h3>
          <button class="btn-icon" @click="showEditModal = false">✕</button>
        </div>
        <div class="modal-body" v-if="editingSkill">
          <div class="form-row">
            <label class="form-label">技能名称</label>
            <input
              type="text"
              class="form-input"
              data-testid="input-skill-name"
              v-model="editingSkill.name"
              placeholder="例如: 代码审查"
            />
          </div>
          <div class="form-row">
            <label class="form-label">技能描述</label>
            <input
              type="text"
              class="form-input"
              data-testid="input-skill-description"
              v-model="editingSkill.description"
              placeholder="简要描述技能的用途"
            />
          </div>
          <div class="form-row">
            <label class="form-label">Prompt 模板</label>
            <textarea
              class="form-textarea"
              data-testid="input-skill-content"
              v-model="editingSkill.content"
              rows="8"
              placeholder="输入 Prompt 模板内容..."
            ></textarea>
          </div>
          <div class="form-row" v-if="!isCreating">
            <label class="form-label">状态</label>
            <select class="form-select" v-model="editingSkill.status">
              <option value="active">活跃</option>
              <option value="draft">草稿</option>
              <option value="disabled">已禁用</option>
              <option value="rejected">已拒绝</option>
            </select>
          </div>
        </div>
        <div class="modal-footer">
          <button class="btn-cancel" @click="showEditModal = false">取消</button>
          <button class="btn-save" data-testid="btn-save-skill" @click="handleSave">
            {{ isCreating ? '创建' : '保存' }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>
